### ISSUE TITLE
save fields and restore

### ISSUE THREAD

**Issue by pishguy** [simonpercic/AirCycle#8]
how can i save some fields such as EditText values, List<MyClass> and restore them?

**Comment by simonpercic** [comment]
Hi, AirCycle is not meant for saving and restoring Android widget state values. 

Instead, it's meant to Bind Android Activity lifecycle callbacks to annotated fields (like onCreate, onStart, onResume, onDestroy, etc.).

**Comment by pishguy** [comment]
@simonpercic unfortunately I can't understand this library is for what, i read again read me and source code.what's library useful

**Comment by MahdiPishguy** [comment]
@simonpercic unfortunately I can't understand this library is for what, j read again read me and source code.what's library useful

**Comment by simonpercic** [comment]
I believe you can understand the purpose and usefulness of the library by looking at the examples included in the project at: [Examples](https://github.com/simonpercic/AirCycle/tree/master/example/src/main/java/com/github/simonpercic/example/aircycle).

Clone the repository and run it in Android Studio.
